# Generated by Django 4.2.11 on 2024-12-31 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_cincooni_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='credentials',
            new_name='users',
        ),
    ]
