# Generated by Django 4.2.11 on 2024-12-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_cincooni_1', '0002_rename_credentials_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
