# Generated by Django 4.2.11 on 2025-01-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_cincooni_1', '0003_hello_delete_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hello',
            new_name='Signup_details',
        ),
    ]
